### ISSUE TITLE
[ROGUE/SPELLS] List of rogue spells that have issues

### ISSUE THREAD

**Issue by Crypticaz** [ProjectSkyfire/SkyFire_548#1071]
Posting a list of warrior bugs and their issues to keep track and make PR's later on. Will continue to add to the list of bugs. If I've missed other warrior bugs, post them here and let me know. 

### **Issues:**

**All Specs:**
- [ ] - Fan of Knives - When Fan of Knives is used on multiple enemies, it gives combo points to a random one of them. https://github.com/ProjectSkyfire/SkyFire_548/issues/955
- [ ] - Assassin's Resolve - Assassin's Resolve the spell it self is working as intended, but you always have the passive, no matter what weapons you use. https://github.com/ProjectSkyfire/SkyFire_548/issues/954
- [ ] - Crimson Tempest - Crimson Tempest only does direct damage. https://github.com/ProjectSkyfire/SkyFire_548/issues/953
- [ ]  - Master Poisoner - does nothing https://github.com/ProjectSkyfire/SkyFire_548/issues/952
- [ ]  - Wound Poison - Tooltip bug  https://github.com/ProjectSkyfire/SkyFire_548/issues/949
- [ ] - Glyph of Blind - does nothing https://github.com/ProjectSkyfire/SkyFire_548/issues/946
- [ ] - Relentless Strikes -  does nothing. https://github.com/ProjectSkyfire/SkyFire_548/issues/943
- [ ] - Shroud of Concealment -  keeps party members stealthed even when they attack / cast spells. https://github.com/ProjectSkyfire/SkyFire_548/issues/939
- [ ] - Smoke Bomb - Smoke Bomb is only making the visual effect https://github.com/ProjectSkyfire/SkyFire_548/issues/938
- [ ] - Vanish - https://github.com/ProjectSkyfire/SkyFire_548/issues/935
- [ ] - Redirect - does not transfer existing combo points to target https://github.com/ProjectSkyfire/SkyFire_548/issues/933
- [ ] - Preparation - does not reset the cooldown of any of the spells listed in the tooltip. https://github.com/ProjectSkyfire/SkyFire_548/issues/932
- [ ] - Shadowstep -  can be cast on self.  https://github.com/ProjectSkyfire/SkyFire_548/issues/926
- [ ] - Nerve Strike - Doesn't apply the Nerve Strike debuff when Kidney Shot / Cheap Shot wears off the target. https://github.com/ProjectSkyfire/SkyFire_548/issues/923
- [ ] - Subterfuge - doesn't give the Subterfuge buff when stealth is broken (by attacking or taking damage) https://github.com/ProjectSkyfire/SkyFire_548/issues/922
- Nightstalker - Gives the 20% movement speed. Does not give the 50% damage increase. https://github.com/ProjectSkyfire/SkyFire_548/issues/919

  
**Combat**
- [ ] - Ruthlessness - does not give combo point on finishing moves https://github.com/ProjectSkyfire/SkyFire_548/issues/969
- [ ]  - Revealing Strike - only gives the debuff on the target, but it has no effect. https://github.com/ProjectSkyfire/SkyFire_548/issues/968
- [ ] - Restless Blades - Restless Blades does nothing. https://github.com/ProjectSkyfire/SkyFire_548/issues/967
- [ ] - Killing Spree https://github.com/ProjectSkyfire/SkyFire_548/issues/966
- [ ] - Combat Potency - Combat Potency has a 100% proc rate. Every off-hand attack restores 15 energy. https://github.com/ProjectSkyfire/SkyFire_548/issues/965
- [ ] - Bandit's Guile - Bandit's Guile does nothing. https://github.com/ProjectSkyfire/SkyFire_548/issues/964

**Assassination**
- [ ] - Venomous Wounds -  does nothing https://github.com/ProjectSkyfire/SkyFire_548/issues/963
- [ ] - Cut to the Chase - does not doing anything. https://github.com/ProjectSkyfire/SkyFire_548/issues/957
- [ ] - Blindside - https://github.com/ProjectSkyfire/SkyFire_548/issues/956

**Subtlety**
- [ ] - Honor Among Thieves - Honor Among Thieves does nothing.
- [ ] - Sanguinary Vein - does nothing https://github.com/ProjectSkyfire/SkyFire_548/issues/942

### **Talents**
**All Specs:**

**SF rev. hash/commit:**  https://github.com/ProjectSkyfire/SkyFire_548/commit/3b1ac84784aeee1231dd52ccafbae5ff3dcf21f8

**SFDB version:**  https://github.com/ProjectSkyfire/SkyFire_548/releases/tag/548-21.0

**Operating system:** Windows 10
